###
GET {{$dotenv MISP_BASE_URL}}/servers/getVersion
Authorization: {{$dotenv MISP_KEY}}
Accept: application/json

###
GET {{$dotenv MISP_BASE_URL}}/attributes/restSearch
Authorization: {{$dotenv MISP_KEY}}
Accept: application/json

{
    "timestamp": "1d"
}
###
GET {{$dotenv MISP_BASE_URL}}/attributes/restSearch
Authorization: {{$dotenv MISP_KEY}}
Accept: application/json

{
    "timestamp": "1d",
    "published": true,
    "returnFormat": "stix2"
}
###
GET {{$dotenv MISP_BASE_URL}}/attributes/restSearch
Authorization: {{$dotenv MISP_KEY}}
Accept: application/json

{
    "limit": "1",
    "returnFormat": "json"
}
###
POST {{$dotenv MISP_BASE_URL}}/events/restSearch
Authorization: {{$dotenv MISP_KEY}}
Accept: application/json

{
  "limit": "2",
  "published": true,
  "returnFormat": "stix2"
}
###